export const fakeClients = [
  {
    id: 0,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 1,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 2,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 3,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 4,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 5,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 6,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 7,
    name: 'Gerson',
    notes: 'Programador',
  },
  {
    id: 8,
    name: 'Gerson',
    notes: 'Programador',
  },
];

export const fakeProducts = [
  {
    id: 0,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 1,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 2,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 3,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 4,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 5,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 6,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 7,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 7,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
  {
    id: 9,
    name: 'Coca cola',
    barcode: '123456789',
    img: '/products/cocacola.jpeg',
    quantity: 40,
    buyPrice: 20,
    sellPrice: 30,
  },
];
