import type { Metadata } from "next";

import { inter } from "@/components/assets/fonts";
import Provider from "@/context/Provider";
import '@/components/assets/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Provider>{children}</Provider>  
      </body>
    </html>
  );
}
